### PR TITLE
feature: use ulixee/hero

### PR DESCRIPTION
**Pull request by daveads**
Replaced puppeteer-extra with @ulixee/hero as the headless browser solution.

/claim #13

### CODE REVIEW

**Comment by daveads** [comment]
optimized version... https://github.com/devflowinc/firecrawl-simple/pull/17/commits/0150b8014f8b4f18f14d3b2b644a5f98dcf8c2eb

**Comment by daveads** [comment]
Done.

**Comment by daveads** [comment]
@cdxker  review this too.

**Review by skeptrunedev — APPROVED** [review]

**Pull request merged**
